### ISSUE TITLE
Error in ubuntu while creating the crud.

### ISSUE THREAD

**Issue by shankhadevpadam** [LaravelDaily/quickadmin#1] opened 2015-11-26 11:16 UTC
I have successfully installed the package and run well. But there is a problem when creating the new crud "Blog" a error is occur, a new folder and controller is create inside the app folder "Http\Controllers\Admin" and controller "Http\Controllers\Admin\BlogController.php"

**Comment by LaravelDaily** [comment] 2015-11-26 11:22
Hi, great first feedback, thanks a lot. 
Forgot to mention in the docs - QuickAdmin generates Controllers so it needs write rights to folders: /app, /app/Http/Controllers, /app/Http/Requests, /database/migrations, /resources/views.
Please assign write rights there, and try again, meanwhile we will try to update package to create writeable folders and will update readme file.

**Comment by shankhadevpadam** [comment] 2015-11-26 11:49
Thanks for your quick response, but still, i got a same issue.

**Comment by LaravelDaily** [comment] 2015-11-26 11:52
Ok, we're fixing the issue at the moment. Probably the problem is with newly created Admin folder. Do you have writeable rights on app/Http/Controllers/Admin ? (we are now testing it, trying to create folder with writeable rights already).

**Comment by shankhadevpadam** [comment] 2015-11-26 12:00
Mate, i have create the Admin folder inside the controller directory with right permission but still got same problem.

**Comment by LaravelDaily** [comment] 2015-11-26 12:02
Ok, first of all thank you for spending time on this and for helping, I really appreciate it.
Could you then describe some details about the problem? What is the exact error message or something in Laravel log file? Maybe it's not about folder permissions at all..

**Comment by shankhadevpadam** [comment] 2015-11-26 12:09
local.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Admin\BlogController does not exist' in /home/padam/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php:737

**Comment by LaravelDaily** [comment] 2015-11-26 12:13
Hmm.. Ok, so my version: you didn't have writeable rights on the folder, so Controller creation failed, and now it's not found. Could you please start from fresh install of Laravel and package? Or at least create a new CRUD and see if it works? Thanks again for the help.

**Comment by fosron** [comment] 2015-11-26 12:34
Mac OS 10.11, same issue, though writing permissions should not be a problem here.

**Comment by LaravelDaily** [comment] 2015-11-26 13:17
Update on the situation: tried on Homestead, Ubuntu, Windows (XAMPP and Wamp) - cannot reproduce the issue. Will be trying. If anyone has the same situation, please give more details which could help us.

**Comment by arku31** [comment] 2015-11-26 14:24
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
php -m here http://pastebin.ru/MdeQ0LrQ

video is here https://yadi.sk/i/V_RiYnNOkkoeY

**Comment by ModestasV** [comment] 2015-11-26 14:58
Hello arku31, I'm glad that you reported this bug.

In your video you showed your fast mistakes and we will look into them (probably we will add notice to enter the directory before installing our package).

The next thing we saw was that it didn't create the folder `App\Http\Controllers\Admin` so the controller was not created. Maybe there is something wrong with creating files in your application. Could you try to make `App\Http\Controllers` writable and try to create new CRUD again? We are unable to get the same result you get.

We will try to fix this bug as soon as possible.

**Comment by arku31** [comment] 2015-11-26 15:24
I got a folder http://joxi.ru/Q2KY67qU9bnkVr  and this is also shown by "ls" command http://joxi.ru/L21zabJs6G5ozA

I guess thats the problem.

**Comment by ModestasV** [comment] 2015-11-26 15:38
@arku31 Could you try to update the package and create new CRUD?

**Comment by arku31** [comment] 2015-11-26 16:28
@ModestasV only tomorrow at 7:00 gmt. I guess someone else in this thread could try to do it early.. The main phase was passed :)

**Comment by w00p** [comment] 2015-11-26 19:25
Great work guys. I Can confirm that this problem is now fixed. Did a new install, and it now works.
I have some other issues. Will make a new topic

**Comment by ModestasV** [comment] 2015-11-26 20:18
Thanks for the report and great help!

Closing this issue for now.

**Closed by ModestasV** 2015-11-26 20:18 UTC
Labels: bug
