### ISSUE TITLE
Create New Crud Controller: Undefined property: stdClass::$column_name

### ISSUE THREAD

**Issue by itelmenko** [LaravelDaily/quickadmin#117] opened 2017-08-03 18:09 UTC
Larevel v5.4.32
Mysql Server version: 8.0.2-dmr MySQL Community Server (GPL)
laraveldaily/quickadmin: 2.1.1

Domain quickadmin.local is my local site
I go to http://quickadmin.local/admin/menu , push the button "Create New Crud Controller"
The I see error in http://quickadmin.local/admin/menu

```

(1/1) ErrorExceptionUndefined property: stdClass::$column_name
--
in MySqlProcessor.php (line 16)
at HandleExceptions->handleError(8, 'Undefined property: stdClass::$column_name', '/var/www/admin-panel/quickadmin/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/MySqlProcessor.php', 16, array('result' => object(stdClass)))in MySqlProcessor.php (line 16)
at MySqlProcessor->Illuminate\Database\Query\Processors\{closure}(object(stdClass))
at array_map(object(Closure), array(object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass),object(stdClass)))in MySqlProcessor.php (line 17)
at MySqlProcessor->processColumnListing(array(object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass), object(stdClass),object(stdClass), object(stdClass)))in MySqlBuilder.php (line 36)
at MySqlBuilder->getColumnListing('users')in Facade.php (line 221)
at Facade::__callStatic('getColumnListing', array('users'))in QuickadminMenuController.php (line 88)
at QuickadminMenuController->createCrud()
at call_user_func_array(array(object(QuickadminMenuController), 'createCrud'), array())in Controller.php (line 55)
at Controller->callAction('createCrud', array())in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(QuickadminMenuController), 'createCrud')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HasPermissions.php (line 21)
at HasPermissions->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in SubstituteBindings.php (line 41)
at SubstituteBindings->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php (line 30)
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ValidatePostSize.php (line 27)
at ValidatePostSize->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 53)



```

**Comment by PovilasKorop** [comment] 2017-08-04 06:08
@itelmenko did you do something manually with `users` DB table? And did you install quickadmin on **fresh** Laravel instance? Cause it seems that MySQL cannot find a column in your users table, so I assume you changes something manually there.

**Comment by itelmenko** [comment] 2017-08-04 07:59
Hi @PovilasKorop ! No, I did not do anything manually with users table.
Yes, I try it on fresh Laravel instance.

**Comment by ModestasV** [comment] 2017-08-04 08:15
@itelmenko What php version are you using?

**Comment by itelmenko** [comment] 2017-08-04 08:18
PHP Version: PHP 7.1.4-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 22:12:32) ( NTS )

**Comment by itelmenko** [comment] 2017-08-04 13:49
BTW. I used laradock with mysql container `docker-compose up -d nginx php-fpm mysql workspace`
Now I try mariadb. And with mariadb I have not this error

**Comment by PovilasKorop** [comment] 2017-08-04 15:35
@itelmenko to be honest, we didn't test the package with laradock or your particular setup. And we didn't have any similar bugs reported during 2 years of package existance. So I would assume it's something with your server anyway. Or could it be that you didn't run migrations properly and then some DB table/field was missing?

Currently we cannot reproduce the bug.

**Comment by itelmenko** [comment] 2017-08-04 17:31
I don't think any migration was missing. I get same error with 3 another laravel admin panels. I think reason is in mysql  version, or adapter or somethink like this. Because If I switch my environment to mariadb, it works fine.
If it is interesting for you I can send DB dump, sample project code.
But it must be set up in laradock.
If it is not interesting for you, you can just close the issue :)
In any case, thank you for help!

**Comment by PovilasKorop** [comment] 2017-08-05 05:55
@itelmenko yeah, I guess we shouldn't spend our time on investigating what seems to be edge-case with Laradock, which I haven't even tried (only read about it). So closing the issue, and thanks for all the information!

**Closed by PovilasKorop** 2017-08-05 05:55 UTC
